apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inforiver.name" . }}-comment-worker
  namespace: {{ include "inforiver.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "inforiver.name" . }}-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "inforiver.name" . }}-app
    spec:
      containers:
      - env:
        - name: ADMIN_PORTAL_URL
          value: {{ .Values.env.ADMIN_PORTAL_URL }}
        - name: SERVICE_NAME
          value: commentWorker
        image: "{{ .Values.image.repository }}/turing-worker:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        name: {{ include "inforiver.name" . }}-comment-worker
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
      imagePullSecrets:
      - name: {{ include "inforiver.name" . }}-docker-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30