apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inforiver.name" . }}-job-api-role-binding
  namespace: {{ include "inforiver.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "inforiver.name" . }}-job-api-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ include "inforiver.name" . }}