apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inforiver.name" . }}-job-api-role
  namespace: {{ include "inforiver.name" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - jobs
  verbs:
  - '*'