apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inforiver.name" . }}-docker-secret
  namespace: {{ include "inforiver.name" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}