apiVersion: v1
kind: Service
metadata:
  name: {{ include "inforiver.name" . }}-api-service
  namespace: {{ include "inforiver.name" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: {{ include "inforiver.name" . }}-loadbalancer
    service.beta.kubernetes.io/aws-load-balancer-subnets: "{{ .Values.loadbalancer.PUB_SUBNET_ID }}, {{ .Values.loadbalancer.APP_SUBNET_NAME }}"
spec:
  selector:
    app: {{ include "inforiver.name" . }}-app
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.ports.sourcePort }}
    targetPort: {{ .Values.ports.containerPort }}
